### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by neerfix** [PyxyApp/Administration#6]
# Web application

## Statistiques
- [x] Dashboard (Show stats)

## Users
- [x] Users pages
- [x] User's infos
- [x] Pages to create a new user 
- [x] Delete Function

## Categories
- [x] Categories pages
- [x] Category's infos
- [x] Pages to create a new category 
- [x] Delete Function

## Lists
- [x] Lists pages
- [x] List's infos
- [x] Pages to create a new list 
- [x] Delete Function

## Tasks
- [x] Tasks pages
- [x] Task's infos
- [x] Pages to create a new task 
- [x] Delete Function

## Other
- [x] Login page
